### PR TITLE
Traefik: Expose murdock frontend and traefik internal metrics

### PR DESCRIPTION
**Pull request by bergzand**
This PR exposes the murdock frontend metrics and the traefik internal metrics so that they can be scraped by a prometheus instance

### CODE REVIEW

**Comment by bergzand** [comment]
Is there documentation on how to test this on the murdock testing instance?

**Comment by aabadie** [comment]
There's no documentation ;)
Otherwise you can probably try it locally first (I guess that's what you did already). On staging, you can fetch the PR (`git fetch origin pull/19/head:traefik-metrics && git checkout traefik-metrics`) and restart the docker-compose.

**Comment by bergzand** [comment]
> Otherwise you can probably try it locally first (I guess that's what you did already).

Tried this already yes. Works fine locally, I promise :)

**Review by aabadie — APPROVED** [review]
> Works fine locally, I promise :)

I trust your testing :) (and changes look good)

**Comment by bergzand** [comment]
Thanks!

**Pull request merged**
